### ISSUE TITLE
Build gpu_nms file:  cannot find -lcublas

### ISSUE THREAD

**Issue by struCoder** [philferriere/dlwin#44]
Hi.
I have follow your steps build DL env on windows. 
But when i run `python setup_gpu.py build` script from [py-faster-rcnn-windows](https://github.com/MrGF/py-faster-rcnn-windows) i got this problems, in my system, there was no `D:\toolkits\Anaconda3\envs\dlwin36\PCbuild\amd64` directory, so `g++` can not found cublas lib.
How can i solve this problem? i have searched a lot from google, but not found the good way to solve this.

Hope get some help from you.
THANKS.
```bash
D:\toolkits\Anaconda3\envs\dlwin36\Library\mingw-w64\bin\g++.exe --shared -s build\temp.win-amd64-3.5\Release\nms\gpu_nms.o build\temp.win-amd64-3.5\Release\nms\gpu_nms.cp35-win_amd64.def -LD:\toolkits\Anaconda3\envs\dlwin36\libs -LD:\toolkits\Anaconda3\envs\dlwin36\PCbuild\amd64 -lcublas -lpython35 -lmsvcr140 -o build\lib.win-amd64-3.5\nms\gpu_nms.cp35-win_amd64.pyd
D:/toolkits/Anaconda3/envs/dlwin36/Library/mingw-w64/bin/../lib/gcc/x86_64-w64-mingw32/5.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lcublas
collect2.exe: error: ld returned 1 exit status
error: command 'D:\\toolkits\\Anaconda3\\envs\\dlwin36\\Library\\mingw-w64\\bin\\g++.exe' failed with exit status 1


```

**Comment by apacha** [comment]
Are you sure that you followed the tutorial? We do not use MinGW anymore since July and there we used version 5.4.0 instead of 5.3.0. Have you tried uninstall MinGW? Were you able to complete our tutorial successfully and then failed at py-faster-rcnn-windows?

Little side-note: If you are just interested in Faster-R-CNN for Windows, check out the [Tensorflow Object Detection API in the Model repo](https://github.com/tensorflow/models/tree/master/research/object_detection). They have implemented not only Faster R-CNN but also other detectors there and they are working very nicely on Windows too.

**Comment by struCoder** [comment]
@apacha 
Thank you for your reply
I have run `Keras` demo success with `CNTK`, `Tensorflow-gpu` and `Theano`.
I found that `python35` and `msvcr140` file was in `D:\toolkits\Anaconda3\envs\dlwin36\libs` but no `cublas`. `cublas` files was  in the other directory. 
Should i  compile it with some tools?

Thanks.

**Comment by apacha** [comment]
If you have been able to successfully run the demos with all three backends, what exactly is the issue? Are you trying to run Theano + cublas? If that does not work, use Theano without cublas or any of the other backends. Note that Theano is no longer officially maintained.
